### ISSUE TITLE
advancements support

### ISSUE THREAD

**Issue by IZeeXeS** [itHotL/PlayerStats#137]
stat advancement ... (any advancement or total number)

**Comment by Artemis-the-gr8** [comment]
What do you mean with this? Do you want the option to grant custom advancements if a stat reaches a certain number?

**Comment by IZeeXeS** [comment]
> What do you mean with this? Do you want the option to grant custom advancements if a stat reaches a certain number?

just a total advancements number per player, i think giving custom advancement for this can be cool, if this possible why not

**Comment by Artemis-the-gr8** [comment]
This isn't something I think really fits in the spirit of PlayerStats currently - it's something that could easily be added through a custom datapack, though.
