### ISSUE TITLE
Missing statistic "Time Played"

### ISSUE THREAD

**Issue by r3ps4J** [itHotL/PlayerStats#148]
The "Time Played" statistic is missing while it is defined in the stats/uuid.json files. The key for this statistic inside the json is `minecraft:play_time`. I think the name should be `play_time` within the plugin just like the other statistics.

**Comment by Artemis-the-gr8** [comment]
That statistic is in the plugin - it's the one called `play_one_minute`. If I recall correctly, Minecraft changed that statistic's name to `play_time` somewhat recently (which I agree is a much more sensible name for it), but I am getting the list of statistic names automatically through the Spigot API, and they have not changed the name. It would be too much of a hassle for now to change it manually, and who knows, maybe it'll change in future versions of the Spigot API.
