### ISSUE TITLE
[Question] Data Location

### ISSUE THREAD

**Issue by Valorless** [itHotL/PlayerStats#153]
Hiyo!
I was wondering where the data is stored so I can edit on a few entries.
Due to some complications caused by another plugin, 2 entries in the "Damage Taken" chart have been maxed to Integer.max() (2147483647).
I'd like these removed somehow :)
![image_2024-05-12_022906515](https://github.com/itHotL/PlayerStats/assets/46874241/7b19c2dd-89f7-4285-9137-e37515ab1acf)

**Comment by Artemis-the-gr8** [comment]
PlayerStats doesn't create its own files for statistics, it uses the data that your server stores - so you can find it in the world/playerdata folder!
